### ISSUE TITLE
Ctrl+V Pasting Images

### ISSUE THREAD

**Issue by HenryTheVacuum** [lefterisgar/caprine#5]
Ctrl+V pasting images into message box pastes 2 of the image instead of 1.

Windows 10 v2.55.7-1 and has been happening in previous versions as well.

**Comment by lefterisgar** [comment]
I can also replicate it on Windows. On Linux it doesn't happen though. I will check to see if something can be done about it. Seems upstream related.

**Comment by lefterisgar** [comment]
Hi! The issue should be fixed in the latest release.
