### ISSUE TITLE
web links shows empty image placeholder

### ISSUE THREAD

**Issue by rosoau** [lefterisgar/caprine#8]
When I post a link to a website or content thereof I get an empty window
![Messenger_004](https://user-images.githubusercontent.com/13397926/178600543-59b58724-9e74-4745-8aa7-1c42ff57b3f1.jpg)

**Comment by lefterisgar** [comment]
What is your OS? Possibly related to #6.

**Comment by rosoau** [comment]
The OS is Ubuntu 22.04. 
Now today this empty window shows
a download option
which was not shown yesterday
![Messenger_005](https://user-images.githubusercontent.com/13397926/178616332-64c37130-5f07-42e4-a215-fc249fb082e4.jpg)

Perhaps changes on FB's side?

**Comment by lefterisgar** [comment]
Who knows what might have happened. I suppose it works fine on your browser, right?

**Comment by rosoau** [comment]
Messenger works the same in the browser.
The Facebook webpage is a jungle to me
that is why I only use Caprine
so I can communicate with family and friends
I am happy with it and can do all I want
these were minor issues 
and you are right about the iceberg

I have to make sure to logout of the browser
before opening Caprine
And whenever there is an update I do delete -R
~/.conf/Caprine and just save my special custom.css

I must say that you guys are extremely courageous
to take on this ever changing labyrinth of a project
You are digital heroes. Thanks to all involved!

**Comment by rosoau** [comment]
I have a feeling that the link thumbnailer could not handle the size of the link (85 MB)
The link to the page with the image download options did show a thumbnail.
![Messenger_007](https://user-images.githubusercontent.com/13397926/179137208-cbe331d2-dbe6-4f53-814d-525d7271fbbe.jpg)

**Comment by lefterisgar** [comment]
Then it's definitely Electron related.

**Comment by rosoau** [comment]
And that is not all. Occasionally Caprine opens with the header of the FB webpage and an empty window below it. Today it opened with a: "Oooops, something went wrong" and then this variant
![Messenger | Page Not Found_001](https://user-images.githubusercontent.com/13397926/179429488-ead6cadc-7d60-46fb-9956-f1655a479479.jpg)
The 2nd login usually brings it up properly

**Comment by lefterisgar** [comment]
> When I post a link to a website or content thereof I get an empty window ![Messenger_004](https://user-images.githubusercontent.com/13397926/178600543-59b58724-9e74-4745-8aa7-1c42ff57b3f1.jpg)

Hi! I have made an attempt at fixing this bug.
Can you try again and see if the picture loads?

**Comment by lefterisgar** [comment]
> And that is not all. Occasionally Caprine opens with the header of the FB webpage and an empty window below it. Today it opened with a: "Oooops, something went wrong" and then this variant ![Messenger | Page Not Found_001](https://user-images.githubusercontent.com/13397926/179429488-ead6cadc-7d60-46fb-9956-f1655a479479.jpg) The 2nd login usually brings it up properly

Please file another issue so we can track it separately.

**Comment by lefterisgar** [comment]
Closing it as stale. My tests show that the newest version fixes the issue. Feel free to reopen if you think otherwise.
